import Script from "next/script";
import Navbar from "@/components/Navbar";
import "../public/css/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}

        <Script src="./js/script.js" />
      </body>
    </html>
  );
}
