import Script from "next/script";
import Navbar from "@/components/Navbar";
import "../public/css/globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Rajib Mia Rahid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        <Script src="./js/script.js" />
      </body>
    </html>
  );
}
